language: go
sudo: false

env:
  global:
  - GO15VENDOREXPERIMENT='1'

branches:
  only:
    - master

go:
 - 1.7.4

os:
 - linux

before_install:
  - go get github.com/mattn/goveralls 

script:
 - make
 - $HOME/gopath/bin/goveralls -service=travis-ci